version: '3'

services:
  database:
    container_name: mysql-database
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: fatec
    ports:
      - '3306:3306'